#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class ADSource:
  UNKNOWN = 0
  APIOFFER = 1
  MYOFFER = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "APIOFFER",
    2: "MYOFFER",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "APIOFFER": 1,
    "MYOFFER": 2,
  }

class PublisherStatus:
  UNKNOWN = 0
  ACTIVE = 1
  PENDING = 2
  BLOCKED = 3

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
    2: "PENDING",
    3: "BLOCKED",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
    "PENDING": 2,
    "BLOCKED": 3,
  }

class AppStatus:
  UNKNOWN = 0
  PENDING = 1
  DISAPPROVED = 2
  PAUSED = 3
  RUNNING = 4
  DELETED = 5

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "PENDING",
    2: "DISAPPROVED",
    3: "PAUSED",
    4: "RUNNING",
    5: "DELETED",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "PENDING": 1,
    "DISAPPROVED": 2,
    "PAUSED": 3,
    "RUNNING": 4,
    "DELETED": 5,
  }

class UnitStatus:
  UNKNOWN = 0
  ACTIVE = 1
  PAUSED = 2
  DELETED = 3

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
    2: "PAUSED",
    3: "DELETED",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
    "PAUSED": 2,
    "DELETED": 3,
  }

class CampaignStatus:
  UNKNOWN = 0
  ACTIVE = 1
  PAUSED = 2
  DELETED = 3
  PENDING = 4
  REJECTED = 5
  UNFINISHED = 6
  REVIEW = 7
  OUT_OF_DAILY_BUDGET = 8
  OUT_OF_TOTAL_BUDGET = 9
  BALACNE = 10
  DAILY_CAP = 11
  PAUSED_FROM_ACTIVE = 12
  PAUSED_FROM_PENDING = 13

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
    2: "PAUSED",
    3: "DELETED",
    4: "PENDING",
    5: "REJECTED",
    6: "UNFINISHED",
    7: "REVIEW",
    8: "OUT_OF_DAILY_BUDGET",
    9: "OUT_OF_TOTAL_BUDGET",
    10: "BALACNE",
    11: "DAILY_CAP",
    12: "PAUSED_FROM_ACTIVE",
    13: "PAUSED_FROM_PENDING",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
    "PAUSED": 2,
    "DELETED": 3,
    "PENDING": 4,
    "REJECTED": 5,
    "UNFINISHED": 6,
    "REVIEW": 7,
    "OUT_OF_DAILY_BUDGET": 8,
    "OUT_OF_TOTAL_BUDGET": 9,
    "BALACNE": 10,
    "DAILY_CAP": 11,
    "PAUSED_FROM_ACTIVE": 12,
    "PAUSED_FROM_PENDING": 13,
  }

class AdvertiserStatus:
  UNKNOWN = 0
  ACTIVE = 1

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
  }

class ConfigStatus:
  UNKNOWN = 0
  ACTIVE = 1

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
  }

class Orientation:
  UNKNOWN = 0
  VERTICAL = 1
  HORIZONTAL = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "VERTICAL",
    2: "HORIZONTAL",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "VERTICAL": 1,
    "HORIZONTAL": 2,
  }

class RequestType:
  UNKNOWN = 0
  SDK = 1
  SITE = 2
  OPENAPI_V2 = 3
  OLD_SDK = 4
  AGENTAPI = 5
  SITE_OLD = 6
  OPENAPI_V3 = 7
  DSP = 8
  OPENAPI_V4 = 9
  ONLINE_API = 10

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "SDK",
    2: "SITE",
    3: "OPENAPI_V2",
    4: "OLD_SDK",
    5: "AGENTAPI",
    6: "SITE_OLD",
    7: "OPENAPI_V3",
    8: "DSP",
    9: "OPENAPI_V4",
    10: "ONLINE_API",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "SDK": 1,
    "SITE": 2,
    "OPENAPI_V2": 3,
    "OLD_SDK": 4,
    "AGENTAPI": 5,
    "SITE_OLD": 6,
    "OPENAPI_V3": 7,
    "DSP": 8,
    "OPENAPI_V4": 9,
    "ONLINE_API": 10,
  }

class DirectMarket:
  UNKNOWN = 0
  NO_LIMIT = 1
  NO_APK = 2
  ONLY_APK = 3
  ONLY_GP = 4

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "NO_LIMIT",
    2: "NO_APK",
    3: "ONLY_APK",
    4: "ONLY_GP",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "NO_LIMIT": 1,
    "NO_APK": 2,
    "ONLY_APK": 3,
    "ONLY_GP": 4,
  }

class SiteIntegrationType:
  JSSDK = 1
  WX = 2

  _VALUES_TO_NAMES = {
    1: "JSSDK",
    2: "WX",
  }

  _NAMES_TO_VALUES = {
    "JSSDK": 1,
    "WX": 2,
  }

class EndCardStoreKitSwitch:
  ON = 1
  OFF = 2

  _VALUES_TO_NAMES = {
    1: "ON",
    2: "OFF",
  }

  _NAMES_TO_VALUES = {
    "ON": 1,
    "OFF": 2,
  }

class CampaignType:
  UNKNOWN = 0
  APPSTORE = 1
  GooglePlay = 2
  APK = 3
  OTHER = 4
  IPA = 5
  SUBSCRIPTION = 6
  WEBSITE = 7

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "APPSTORE",
    2: "GooglePlay",
    3: "APK",
    4: "OTHER",
    5: "IPA",
    6: "SUBSCRIPTION",
    7: "WEBSITE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "APPSTORE": 1,
    "GooglePlay": 2,
    "APK": 3,
    "OTHER": 4,
    "IPA": 5,
    "SUBSCRIPTION": 6,
    "WEBSITE": 7,
  }

class Platform:
  UNKNOWN = 0
  ANDROID = 1
  IOS = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ANDROID",
    2: "IOS",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ANDROID": 1,
    "IOS": 2,
  }

class Category:
  UNKNOWN = 0
  GAME = 1
  APPLICATION = 2
  BRAND = 3
  E_COMMERCE = 4

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "GAME",
    2: "APPLICATION",
    3: "BRAND",
    4: "E_COMMERCE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "GAME": 1,
    "APPLICATION": 2,
    "BRAND": 3,
    "E_COMMERCE": 4,
  }

class NetworkType:
  UNKNOWN = 0
  NET_2G = 2
  NET_3G = 3
  NET_4G = 4
  NET_WIFI = 9
  RECALL_IF_UNKNOWN = 10

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    2: "NET_2G",
    3: "NET_3G",
    4: "NET_4G",
    9: "NET_WIFI",
    10: "RECALL_IF_UNKNOWN",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "NET_2G": 2,
    "NET_3G": 3,
    "NET_4G": 4,
    "NET_WIFI": 9,
    "RECALL_IF_UNKNOWN": 10,
  }

class PublisherType:
  UNKNOWN = 0
  ADN = 1
  MEDIABUY = 2
  M = 3
  HAHAMOBI = 4
  MOBPOWER = 6
  MVDETECTIVE = 99

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ADN",
    2: "MEDIABUY",
    3: "M",
    4: "HAHAMOBI",
    6: "MOBPOWER",
    99: "MVDETECTIVE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ADN": 1,
    "MEDIABUY": 2,
    "M": 3,
    "HAHAMOBI": 4,
    "MOBPOWER": 6,
    "MVDETECTIVE": 99,
  }

class BtType:
  NORMALFFER = 0
  BTOFFER = 1

  _VALUES_TO_NAMES = {
    0: "NORMALFFER",
    1: "BTOFFER",
  }

  _NAMES_TO_VALUES = {
    "NORMALFFER": 0,
    "BTOFFER": 1,
  }

class ImageSizeEnum:
  UNKNOWN = 0
  NONE = 1
  SIZE_320x50 = 2
  SIZE_300x250 = 3
  SIZE_480x320 = 4
  SIZE_320x480 = 5
  SIZE_300x300 = 6
  SIZE_1200x627 = 7
  SIZE_REWARDED_VIDEO = 8
  SIZE_INTERACTIVE = 9
  SIZE_710x396 = 13
  SIZE_690x388 = 14
  SIZE_288x150 = 15
  SIZE_428x238 = 16
  SIZE_1080x540 = 17

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "NONE",
    2: "SIZE_320x50",
    3: "SIZE_300x250",
    4: "SIZE_480x320",
    5: "SIZE_320x480",
    6: "SIZE_300x300",
    7: "SIZE_1200x627",
    8: "SIZE_REWARDED_VIDEO",
    9: "SIZE_INTERACTIVE",
    13: "SIZE_710x396",
    14: "SIZE_690x388",
    15: "SIZE_288x150",
    16: "SIZE_428x238",
    17: "SIZE_1080x540",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "NONE": 1,
    "SIZE_320x50": 2,
    "SIZE_300x250": 3,
    "SIZE_480x320": 4,
    "SIZE_320x480": 5,
    "SIZE_300x300": 6,
    "SIZE_1200x627": 7,
    "SIZE_REWARDED_VIDEO": 8,
    "SIZE_INTERACTIVE": 9,
    "SIZE_710x396": 13,
    "SIZE_690x388": 14,
    "SIZE_288x150": 15,
    "SIZE_428x238": 16,
    "SIZE_1080x540": 17,
  }

class ADType:
  UNKNOWN = 0
  BANNER = 2
  APPWALL = 3
  INTERSTITIAL = 29
  NATIVE = 42
  REWARDED_VIDEO = 94
  FEEDS_VIDEO = 95
  RECTANGULAR = 215
  REFFERLINK = 216
  OFFERWALL = 278
  INTERSTITIAL_SDK = 279
  MOBPOWER = 280
  ONLINE_VIDEO = 284
  JS_NATIVE_VIDEO = 285
  JS_BANNER_VIDEO = 286
  INTERSTITIAL_VIDEO = 287
  INTERACTIVE = 288
  JM_ICON = 289
  WX_NATIVE = 291
  WX_APPWALL = 292
  WX_BANNER = 293
  WX_REWARD_IMAGE = 294
  MORE_OFFER = 295
  SDK_BANNER = 296
  SPLASH = 297
  NATIVE_H5 = 298

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    2: "BANNER",
    3: "APPWALL",
    29: "INTERSTITIAL",
    42: "NATIVE",
    94: "REWARDED_VIDEO",
    95: "FEEDS_VIDEO",
    215: "RECTANGULAR",
    216: "REFFERLINK",
    278: "OFFERWALL",
    279: "INTERSTITIAL_SDK",
    280: "MOBPOWER",
    284: "ONLINE_VIDEO",
    285: "JS_NATIVE_VIDEO",
    286: "JS_BANNER_VIDEO",
    287: "INTERSTITIAL_VIDEO",
    288: "INTERACTIVE",
    289: "JM_ICON",
    291: "WX_NATIVE",
    292: "WX_APPWALL",
    293: "WX_BANNER",
    294: "WX_REWARD_IMAGE",
    295: "MORE_OFFER",
    296: "SDK_BANNER",
    297: "SPLASH",
    298: "NATIVE_H5",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "BANNER": 2,
    "APPWALL": 3,
    "INTERSTITIAL": 29,
    "NATIVE": 42,
    "REWARDED_VIDEO": 94,
    "FEEDS_VIDEO": 95,
    "RECTANGULAR": 215,
    "REFFERLINK": 216,
    "OFFERWALL": 278,
    "INTERSTITIAL_SDK": 279,
    "MOBPOWER": 280,
    "ONLINE_VIDEO": 284,
    "JS_NATIVE_VIDEO": 285,
    "JS_BANNER_VIDEO": 286,
    "INTERSTITIAL_VIDEO": 287,
    "INTERACTIVE": 288,
    "JM_ICON": 289,
    "WX_NATIVE": 291,
    "WX_APPWALL": 292,
    "WX_BANNER": 293,
    "WX_REWARD_IMAGE": 294,
    "MORE_OFFER": 295,
    "SDK_BANNER": 296,
    "SPLASH": 297,
    "NATIVE_H5": 298,
  }

class ADTemplate:
  UNKNOWN = 0
  SINGLE_PIC = 1
  MULTI_ELEMENT = 2
  MULTI_ICONS = 3
  JS_BANNER = 4
  JS_FULLSCREEN = 5
  JS_LISTBLOCK = 6
  JS_PAGEBLOCK = 7
  JS_REFFERLINK = 8
  REWARDED_VIDEO = 9

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "SINGLE_PIC",
    2: "MULTI_ELEMENT",
    3: "MULTI_ICONS",
    4: "JS_BANNER",
    5: "JS_FULLSCREEN",
    6: "JS_LISTBLOCK",
    7: "JS_PAGEBLOCK",
    8: "JS_REFFERLINK",
    9: "REWARDED_VIDEO",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "SINGLE_PIC": 1,
    "MULTI_ELEMENT": 2,
    "MULTI_ICONS": 3,
    "JS_BANNER": 4,
    "JS_FULLSCREEN": 5,
    "JS_LISTBLOCK": 6,
    "JS_PAGEBLOCK": 7,
    "JS_REFFERLINK": 8,
    "REWARDED_VIDEO": 9,
  }

class InteractiveResourceType:
  UNKNOWN = 0
  PLAYABLE = 1
  APPWALL = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "PLAYABLE",
    2: "APPWALL",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "PLAYABLE": 1,
    "APPWALL": 2,
  }

class CampaignTag:
  UNKNOWN = 0
  ADMIN = 1
  ADVERTISER = 2
  M_MYOFFER = 3
  BRANDOFFER = 4

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ADMIN",
    2: "ADVERTISER",
    3: "M_MYOFFER",
    4: "BRANDOFFER",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ADMIN": 1,
    "ADVERTISER": 2,
    "M_MYOFFER": 3,
    "BRANDOFFER": 4,
  }

class VCTStatus:
  UNKNOWN = 0
  NOLIMIT = 1
  BRANDADSONLY = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "NOLIMIT",
    2: "BRANDADSONLY",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "NOLIMIT": 1,
    "BRANDADSONLY": 2,
  }

class ExcludeRuleStatus:
  UNKNOWN = 0
  ACTIVE = 1

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
  }

class ExcludeRuleType:
  UNKNOWN = 0
  BLACK = 1
  WHITE = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "BLACK",
    2: "WHITE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "BLACK": 1,
    "WHITE": 2,
  }

class OutputType:
  RETURN_IF_ANY = 1
  RETURN_NULL_IF_NOT_ENOUGH = 2

  _VALUES_TO_NAMES = {
    1: "RETURN_IF_ANY",
    2: "RETURN_NULL_IF_NOT_ENOUGH",
  }

  _NAMES_TO_VALUES = {
    "RETURN_IF_ANY": 1,
    "RETURN_NULL_IF_NOT_ENOUGH": 2,
  }

class PayType:
  UNKNOWN = 0
  CPI = 1
  CPC = 2
  CPM = 3
  CPA = 4
  CPE = 5

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "CPI",
    2: "CPC",
    3: "CPM",
    4: "CPA",
    5: "CPE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "CPI": 1,
    "CPC": 2,
    "CPM": 3,
    "CPA": 4,
    "CPE": 5,
  }

class IsIncent:
  UNKNOWN = 0
  INCENT = 1
  NONINCENT = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "INCENT",
    2: "NONINCENT",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "INCENT": 1,
    "NONINCENT": 2,
  }

class offerSource:
  UNKNOWN = 0
  DIRECT = 1
  DIRECT_MTG = 2
  INDIRECT_MANUAL = 3
  INDIRECT_API = 4

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "DIRECT",
    2: "DIRECT_MTG",
    3: "INDIRECT_MANUAL",
    4: "INDIRECT_API",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "DIRECT": 1,
    "DIRECT_MTG": 2,
    "INDIRECT_MANUAL": 3,
    "INDIRECT_API": 4,
  }

class OfferType:
  UNKNOWN = 0
  VIDEO_REWARD = 1
  DOWNLOAD_REWARD = 2
  CPA = 3
  VBA = 99

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "VIDEO_REWARD",
    2: "DOWNLOAD_REWARD",
    3: "CPA",
    99: "VBA",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "VIDEO_REWARD": 1,
    "DOWNLOAD_REWARD": 2,
    "CPA": 3,
    "VBA": 99,
  }

class OfferTag:
  UNKNOWN = 0
  VBA_EXCLUDE_PACKAGE = 1

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "VBA_EXCLUDE_PACKAGE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "VBA_EXCLUDE_PACKAGE": 1,
  }

class OfferPreferenceType:
  UNKNOWN = 0
  APPSTORE = 1
  GOOGLE_PLAY = 2
  APK = 3
  BRAND_ADS = 4
  ABLIGATED_TO_CONTENT_RATING = 5
  ALLOW_INCENT_OFFER = 6
  BILLING_TYPE_CPM = 7
  BILLING_TYPE_CPC = 8
  BILLING_TYPE_CPI = 9
  BILLING_TYPE_CPA = 10

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "APPSTORE",
    2: "GOOGLE_PLAY",
    3: "APK",
    4: "BRAND_ADS",
    5: "ABLIGATED_TO_CONTENT_RATING",
    6: "ALLOW_INCENT_OFFER",
    7: "BILLING_TYPE_CPM",
    8: "BILLING_TYPE_CPC",
    9: "BILLING_TYPE_CPI",
    10: "BILLING_TYPE_CPA",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "APPSTORE": 1,
    "GOOGLE_PLAY": 2,
    "APK": 3,
    "BRAND_ADS": 4,
    "ABLIGATED_TO_CONTENT_RATING": 5,
    "ALLOW_INCENT_OFFER": 6,
    "BILLING_TYPE_CPM": 7,
    "BILLING_TYPE_CPC": 8,
    "BILLING_TYPE_CPI": 9,
    "BILLING_TYPE_CPA": 10,
  }

class ContentRatingNum:
  TWELVE = 12
  SIXTEEN = 16

  _VALUES_TO_NAMES = {
    12: "TWELVE",
    16: "SIXTEEN",
  }

  _NAMES_TO_VALUES = {
    "TWELVE": 12,
    "SIXTEEN": 16,
  }

class ContentPreferenceType:
  UNKNOWN = 0
  ALLOW_MATURE_ADS = 1
  NOT_ALLOW_MATURE_ADS = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ALLOW_MATURE_ADS",
    2: "NOT_ALLOW_MATURE_ADS",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ALLOW_MATURE_ADS": 1,
    "NOT_ALLOW_MATURE_ADS": 2,
  }

class SpecialType:
  UNKNOWN = 0
  APK = 1
  ADULT = 2
  INCENT = 3
  BRAND = 4
  CPA = 5
  GAME = 6
  BUSINESS = 7
  BOOSTER = 8
  LAUCHER = 9
  BROWSER = 10
  COMICS = 11
  COMMUNICATION = 12
  EDUCATION = 13
  FINANCE = 14
  HEALTH_AND_FITNESS = 15
  WALLPAPER = 16
  MEDIA_AND_VIDEO = 17
  MEDICAL = 18
  MUSIC_AND_AUDIO = 19
  NEWS_AND_MAGAZINES = 20
  PHOTOGRAPHY = 21
  E_COMMERCE = 22
  SOCIAL = 23
  SPORTS = 24
  TRANSPORTATION = 25
  TRAVEL_AND_LOCAL = 26
  WEATHER = 27
  DICTIONARY = 28
  BOOK = 29
  KEYBOARD = 30
  BATTERY_SAVER = 31
  OTHERS = 32
  APP_MARKET = 33
  VEHICLE = 34
  JOB_SEARCHING = 35
  MOBILE_RECHARGE = 36
  SCREEN_LOCK = 37
  PRIVACY_TOOL = 38

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "APK",
    2: "ADULT",
    3: "INCENT",
    4: "BRAND",
    5: "CPA",
    6: "GAME",
    7: "BUSINESS",
    8: "BOOSTER",
    9: "LAUCHER",
    10: "BROWSER",
    11: "COMICS",
    12: "COMMUNICATION",
    13: "EDUCATION",
    14: "FINANCE",
    15: "HEALTH_AND_FITNESS",
    16: "WALLPAPER",
    17: "MEDIA_AND_VIDEO",
    18: "MEDICAL",
    19: "MUSIC_AND_AUDIO",
    20: "NEWS_AND_MAGAZINES",
    21: "PHOTOGRAPHY",
    22: "E_COMMERCE",
    23: "SOCIAL",
    24: "SPORTS",
    25: "TRANSPORTATION",
    26: "TRAVEL_AND_LOCAL",
    27: "WEATHER",
    28: "DICTIONARY",
    29: "BOOK",
    30: "KEYBOARD",
    31: "BATTERY_SAVER",
    32: "OTHERS",
    33: "APP_MARKET",
    34: "VEHICLE",
    35: "JOB_SEARCHING",
    36: "MOBILE_RECHARGE",
    37: "SCREEN_LOCK",
    38: "PRIVACY_TOOL",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "APK": 1,
    "ADULT": 2,
    "INCENT": 3,
    "BRAND": 4,
    "CPA": 5,
    "GAME": 6,
    "BUSINESS": 7,
    "BOOSTER": 8,
    "LAUCHER": 9,
    "BROWSER": 10,
    "COMICS": 11,
    "COMMUNICATION": 12,
    "EDUCATION": 13,
    "FINANCE": 14,
    "HEALTH_AND_FITNESS": 15,
    "WALLPAPER": 16,
    "MEDIA_AND_VIDEO": 17,
    "MEDICAL": 18,
    "MUSIC_AND_AUDIO": 19,
    "NEWS_AND_MAGAZINES": 20,
    "PHOTOGRAPHY": 21,
    "E_COMMERCE": 22,
    "SOCIAL": 23,
    "SPORTS": 24,
    "TRANSPORTATION": 25,
    "TRAVEL_AND_LOCAL": 26,
    "WEATHER": 27,
    "DICTIONARY": 28,
    "BOOK": 29,
    "KEYBOARD": 30,
    "BATTERY_SAVER": 31,
    "OTHERS": 32,
    "APP_MARKET": 33,
    "VEHICLE": 34,
    "JOB_SEARCHING": 35,
    "MOBILE_RECHARGE": 36,
    "SCREEN_LOCK": 37,
    "PRIVACY_TOOL": 38,
  }

class OfferSystem:
  M_OFFER = 3
  DSP_OFFER = 5

  _VALUES_TO_NAMES = {
    3: "M_OFFER",
    5: "DSP_OFFER",
  }

  _NAMES_TO_VALUES = {
    "M_OFFER": 3,
    "DSP_OFFER": 5,
  }

class FilterStatus:
  kCheckPass = 0
  kCheckBrandOfferSet = 1
  kCheckIncludePackageNameSet = 2
  kCheckOsVersionCode = 3
  kCheckTimestamp = 4
  kCheckPlatfom = 5
  kCheckCategory = 6
  kCheckDirectMarket = 7
  kCheckNetworkType = 8
  kCheckDeviceModel = 9
  kCheckMobileCode = 10
  kCheckNetWork = 11
  kCheckImageSizeId = 12
  kCheckAdvertiserExists = 13
  kCheckAdvertiserStatus = 14
  kCheckExcludeRule = 15
  kCheckExcludePackageNameSet = 16
  kCheckExcludeCampaignIdSet = 17
  kCheckGaidIdfaNeeds = 18
  kCheckCityCode = 19
  kCheckGaidSetFor107190486 = 20
  kCheckVctStatus = 21
  kCheckTargetPackageNameSet = 22
  kCheckBt = 23
  kCheckPriceFloor = 24
  kCheckContentRating = 25
  kCheckBlockCategory = 26
  kCheckMatureAds = 27
  kCheckMarketType = 28
  kCheckInterstitialSdk = 29
  kCheckSmart = 30
  kCheckFilterDspOffer = 31
  kCheckRetargettingDevid = 32
  kCheckPowerPackList = 33
  kCheckVta = 34
  kCheckTrafficType = 35
  kCheckInterestAndGender = 36
  kCheckAdSchedule = 37
  kCheckUserAge = 38
  kCheckCreativeType = 39
  kCheckVideoAds = 40
  kCheckCleverPackList = 41
  kCheckInstallPackageNameSet = 42
  kCheckRbaRate = 43
  kCheckBillingType = 44
  kCheckLinkType = 45
  kCheckDeviceType = 46
  kCheckTargetUnit = 47
  kCheckIabCategory = 48
  kCheckTargeAdType = 49
  kCheckCPMOffer = 50
  kCheckNormalFilterSecondOffer = 51
  kCheckAdv919Offer = 52
  kCheckAdv903Offer = 53
  kCheckDetectRate = 54
  kCheckFingerPrint = 55
  kCheckCoppa = 56
  kCheckSdkVersionTarget = 57
  kCheckJmIconStatus = 58
  kCheckDeviceLanguage = 59
  kCheckVideoLength = 60
  kCheckSiteIntegrationType = 61
  kCheckUnitAppOfferRule = 62
  kCheckEffectiveCountry = 63
  kGetCreativeInfoFail = 64
  kFilterByOnlineDmp = 65
  kCheckAdSource = 66
  kCheckPublisherId = 67
  kCheckCountryCode = 68
  kCheckBasicCreative = 69
  kCheckTargetAudience = 70
  kCheckMarketCategory = 71

  _VALUES_TO_NAMES = {
    0: "kCheckPass",
    1: "kCheckBrandOfferSet",
    2: "kCheckIncludePackageNameSet",
    3: "kCheckOsVersionCode",
    4: "kCheckTimestamp",
    5: "kCheckPlatfom",
    6: "kCheckCategory",
    7: "kCheckDirectMarket",
    8: "kCheckNetworkType",
    9: "kCheckDeviceModel",
    10: "kCheckMobileCode",
    11: "kCheckNetWork",
    12: "kCheckImageSizeId",
    13: "kCheckAdvertiserExists",
    14: "kCheckAdvertiserStatus",
    15: "kCheckExcludeRule",
    16: "kCheckExcludePackageNameSet",
    17: "kCheckExcludeCampaignIdSet",
    18: "kCheckGaidIdfaNeeds",
    19: "kCheckCityCode",
    20: "kCheckGaidSetFor107190486",
    21: "kCheckVctStatus",
    22: "kCheckTargetPackageNameSet",
    23: "kCheckBt",
    24: "kCheckPriceFloor",
    25: "kCheckContentRating",
    26: "kCheckBlockCategory",
    27: "kCheckMatureAds",
    28: "kCheckMarketType",
    29: "kCheckInterstitialSdk",
    30: "kCheckSmart",
    31: "kCheckFilterDspOffer",
    32: "kCheckRetargettingDevid",
    33: "kCheckPowerPackList",
    34: "kCheckVta",
    35: "kCheckTrafficType",
    36: "kCheckInterestAndGender",
    37: "kCheckAdSchedule",
    38: "kCheckUserAge",
    39: "kCheckCreativeType",
    40: "kCheckVideoAds",
    41: "kCheckCleverPackList",
    42: "kCheckInstallPackageNameSet",
    43: "kCheckRbaRate",
    44: "kCheckBillingType",
    45: "kCheckLinkType",
    46: "kCheckDeviceType",
    47: "kCheckTargetUnit",
    48: "kCheckIabCategory",
    49: "kCheckTargeAdType",
    50: "kCheckCPMOffer",
    51: "kCheckNormalFilterSecondOffer",
    52: "kCheckAdv919Offer",
    53: "kCheckAdv903Offer",
    54: "kCheckDetectRate",
    55: "kCheckFingerPrint",
    56: "kCheckCoppa",
    57: "kCheckSdkVersionTarget",
    58: "kCheckJmIconStatus",
    59: "kCheckDeviceLanguage",
    60: "kCheckVideoLength",
    61: "kCheckSiteIntegrationType",
    62: "kCheckUnitAppOfferRule",
    63: "kCheckEffectiveCountry",
    64: "kGetCreativeInfoFail",
    65: "kFilterByOnlineDmp",
    66: "kCheckAdSource",
    67: "kCheckPublisherId",
    68: "kCheckCountryCode",
    69: "kCheckBasicCreative",
    70: "kCheckTargetAudience",
    71: "kCheckMarketCategory",
  }

  _NAMES_TO_VALUES = {
    "kCheckPass": 0,
    "kCheckBrandOfferSet": 1,
    "kCheckIncludePackageNameSet": 2,
    "kCheckOsVersionCode": 3,
    "kCheckTimestamp": 4,
    "kCheckPlatfom": 5,
    "kCheckCategory": 6,
    "kCheckDirectMarket": 7,
    "kCheckNetworkType": 8,
    "kCheckDeviceModel": 9,
    "kCheckMobileCode": 10,
    "kCheckNetWork": 11,
    "kCheckImageSizeId": 12,
    "kCheckAdvertiserExists": 13,
    "kCheckAdvertiserStatus": 14,
    "kCheckExcludeRule": 15,
    "kCheckExcludePackageNameSet": 16,
    "kCheckExcludeCampaignIdSet": 17,
    "kCheckGaidIdfaNeeds": 18,
    "kCheckCityCode": 19,
    "kCheckGaidSetFor107190486": 20,
    "kCheckVctStatus": 21,
    "kCheckTargetPackageNameSet": 22,
    "kCheckBt": 23,
    "kCheckPriceFloor": 24,
    "kCheckContentRating": 25,
    "kCheckBlockCategory": 26,
    "kCheckMatureAds": 27,
    "kCheckMarketType": 28,
    "kCheckInterstitialSdk": 29,
    "kCheckSmart": 30,
    "kCheckFilterDspOffer": 31,
    "kCheckRetargettingDevid": 32,
    "kCheckPowerPackList": 33,
    "kCheckVta": 34,
    "kCheckTrafficType": 35,
    "kCheckInterestAndGender": 36,
    "kCheckAdSchedule": 37,
    "kCheckUserAge": 38,
    "kCheckCreativeType": 39,
    "kCheckVideoAds": 40,
    "kCheckCleverPackList": 41,
    "kCheckInstallPackageNameSet": 42,
    "kCheckRbaRate": 43,
    "kCheckBillingType": 44,
    "kCheckLinkType": 45,
    "kCheckDeviceType": 46,
    "kCheckTargetUnit": 47,
    "kCheckIabCategory": 48,
    "kCheckTargeAdType": 49,
    "kCheckCPMOffer": 50,
    "kCheckNormalFilterSecondOffer": 51,
    "kCheckAdv919Offer": 52,
    "kCheckAdv903Offer": 53,
    "kCheckDetectRate": 54,
    "kCheckFingerPrint": 55,
    "kCheckCoppa": 56,
    "kCheckSdkVersionTarget": 57,
    "kCheckJmIconStatus": 58,
    "kCheckDeviceLanguage": 59,
    "kCheckVideoLength": 60,
    "kCheckSiteIntegrationType": 61,
    "kCheckUnitAppOfferRule": 62,
    "kCheckEffectiveCountry": 63,
    "kGetCreativeInfoFail": 64,
    "kFilterByOnlineDmp": 65,
    "kCheckAdSource": 66,
    "kCheckPublisherId": 67,
    "kCheckCountryCode": 68,
    "kCheckBasicCreative": 69,
    "kCheckTargetAudience": 70,
    "kCheckMarketCategory": 71,
  }

class CreativeStatus:
  UNKNOWN = 0
  ACTIVE = 1
  PAUSED = 2
  DELETED = 3
  PENDING = 4

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
    2: "PAUSED",
    3: "DELETED",
    4: "PENDING",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
    "PAUSED": 2,
    "DELETED": 3,
    "PENDING": 4,
  }

class CreativeType:
  APP_NAME = 401
  APP_DESC = 402
  APP_RATE = 403
  CTA_BUTTON = 404
  ICON = 405
  COMMENT = 406
  SIZE_320x50 = 101
  SIZE_300x250 = 102
  SIZE_480x320 = 103
  SIZE_320x480 = 104
  SIZE_300x300 = 105
  SIZE_1200x627 = 106
  JS_TAG_320x50 = 107
  JS_TAG_300x250 = 108
  JS_TAG_480x320 = 109
  JS_TAG_320x480 = 110
  JS_TAG_300x300 = 111
  JS_TAG_1200x627 = 112
  VIDEO = 201
  VIDEO_DCO = 8201
  JS_TAG = 202
  BRAND = 301
  SIZE_288x150 = 11001
  SIZE_428x238 = 11004
  SIZE_690x388 = 11009
  SIZE_720x440 = 11010
  SIZE_720x1280 = 11011
  SIZE_1280x720 = 11015
  SIZE_710x396 = 11024
  SIZE_1125x310 = 11042
  SIZE_1080x540 = 11045
  GIF_INDUCED = 12000
  GIF_1200x627 = 12006
  GIF_640x360 = 12018
  GIF_360x640 = 12033
  FULLVIEW_IMAGE = 15001
  FULLVIEW_VIDEO = 26001
  ENDCARD = 50001
  ENDCARD_ZIP = 50002
  ENDCARD_ZIP_DCO = 850002
  PLAYABLE_URL = 61001
  PLAYABLE_ZIP = 61002
  PLAYABLE_ZIP_DCO = 861002
  AR_URL = 61003
  AR_ZIP = 61004
  FULLVIEW_PLAYABLE_URL = 61005
  FULLVIEW_PLAYABLE_ZIP = 61006

  _VALUES_TO_NAMES = {
    401: "APP_NAME",
    402: "APP_DESC",
    403: "APP_RATE",
    404: "CTA_BUTTON",
    405: "ICON",
    406: "COMMENT",
    101: "SIZE_320x50",
    102: "SIZE_300x250",
    103: "SIZE_480x320",
    104: "SIZE_320x480",
    105: "SIZE_300x300",
    106: "SIZE_1200x627",
    107: "JS_TAG_320x50",
    108: "JS_TAG_300x250",
    109: "JS_TAG_480x320",
    110: "JS_TAG_320x480",
    111: "JS_TAG_300x300",
    112: "JS_TAG_1200x627",
    201: "VIDEO",
    8201: "VIDEO_DCO",
    202: "JS_TAG",
    301: "BRAND",
    11001: "SIZE_288x150",
    11004: "SIZE_428x238",
    11009: "SIZE_690x388",
    11010: "SIZE_720x440",
    11011: "SIZE_720x1280",
    11015: "SIZE_1280x720",
    11024: "SIZE_710x396",
    11042: "SIZE_1125x310",
    11045: "SIZE_1080x540",
    12000: "GIF_INDUCED",
    12006: "GIF_1200x627",
    12018: "GIF_640x360",
    12033: "GIF_360x640",
    15001: "FULLVIEW_IMAGE",
    26001: "FULLVIEW_VIDEO",
    50001: "ENDCARD",
    50002: "ENDCARD_ZIP",
    850002: "ENDCARD_ZIP_DCO",
    61001: "PLAYABLE_URL",
    61002: "PLAYABLE_ZIP",
    861002: "PLAYABLE_ZIP_DCO",
    61003: "AR_URL",
    61004: "AR_ZIP",
    61005: "FULLVIEW_PLAYABLE_URL",
    61006: "FULLVIEW_PLAYABLE_ZIP",
  }

  _NAMES_TO_VALUES = {
    "APP_NAME": 401,
    "APP_DESC": 402,
    "APP_RATE": 403,
    "CTA_BUTTON": 404,
    "ICON": 405,
    "COMMENT": 406,
    "SIZE_320x50": 101,
    "SIZE_300x250": 102,
    "SIZE_480x320": 103,
    "SIZE_320x480": 104,
    "SIZE_300x300": 105,
    "SIZE_1200x627": 106,
    "JS_TAG_320x50": 107,
    "JS_TAG_300x250": 108,
    "JS_TAG_480x320": 109,
    "JS_TAG_320x480": 110,
    "JS_TAG_300x300": 111,
    "JS_TAG_1200x627": 112,
    "VIDEO": 201,
    "VIDEO_DCO": 8201,
    "JS_TAG": 202,
    "BRAND": 301,
    "SIZE_288x150": 11001,
    "SIZE_428x238": 11004,
    "SIZE_690x388": 11009,
    "SIZE_720x440": 11010,
    "SIZE_720x1280": 11011,
    "SIZE_1280x720": 11015,
    "SIZE_710x396": 11024,
    "SIZE_1125x310": 11042,
    "SIZE_1080x540": 11045,
    "GIF_INDUCED": 12000,
    "GIF_1200x627": 12006,
    "GIF_640x360": 12018,
    "GIF_360x640": 12033,
    "FULLVIEW_IMAGE": 15001,
    "FULLVIEW_VIDEO": 26001,
    "ENDCARD": 50001,
    "ENDCARD_ZIP": 50002,
    "ENDCARD_ZIP_DCO": 850002,
    "PLAYABLE_URL": 61001,
    "PLAYABLE_ZIP": 61002,
    "PLAYABLE_ZIP_DCO": 861002,
    "AR_URL": 61003,
    "AR_ZIP": 61004,
    "FULLVIEW_PLAYABLE_URL": 61005,
    "FULLVIEW_PLAYABLE_ZIP": 61006,
  }

class VideoAds:
  UNKNOWN = 0
  NO_LIMIT = 1
  NO_VIDEO = 2
  ONLY_VIDEO = 3

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "NO_LIMIT",
    2: "NO_VIDEO",
    3: "ONLY_VIDEO",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "NO_LIMIT": 1,
    "NO_VIDEO": 2,
    "ONLY_VIDEO": 3,
  }

class OfferWallType:
  VIDEO_OFFER = 1
  DIRECT_3S = 2
  NONE_DIRECT_3S = 3
  NONE_3S = 4

  _VALUES_TO_NAMES = {
    1: "VIDEO_OFFER",
    2: "DIRECT_3S",
    3: "NONE_DIRECT_3S",
    4: "NONE_3S",
  }

  _NAMES_TO_VALUES = {
    "VIDEO_OFFER": 1,
    "DIRECT_3S": 2,
    "NONE_DIRECT_3S": 3,
    "NONE_3S": 4,
  }

class DeviceType:
  UNKNOWN = 10
  PHONE = 4
  TABLET = 5

  _VALUES_TO_NAMES = {
    10: "UNKNOWN",
    4: "PHONE",
    5: "TABLET",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 10,
    "PHONE": 4,
    "TABLET": 5,
  }

class AdnAdType:
  BANNER = 1
  DISPLAY_INTERSTITIAL = 2
  DISPALY_NATIVE = 3
  APPWALL = 4
  REWARDED_APPWALL = 5
  INTERSTITIAL_VIDEO = 6
  NATIVE_VIDEO = 7
  REWARDED_VIDEO = 8
  INSTREAM_VIDEO = 9
  INTERACTIVE = 10
  MORE_OFFER = 11
  SPLASH = 12

  _VALUES_TO_NAMES = {
    1: "BANNER",
    2: "DISPLAY_INTERSTITIAL",
    3: "DISPALY_NATIVE",
    4: "APPWALL",
    5: "REWARDED_APPWALL",
    6: "INTERSTITIAL_VIDEO",
    7: "NATIVE_VIDEO",
    8: "REWARDED_VIDEO",
    9: "INSTREAM_VIDEO",
    10: "INTERACTIVE",
    11: "MORE_OFFER",
    12: "SPLASH",
  }

  _NAMES_TO_VALUES = {
    "BANNER": 1,
    "DISPLAY_INTERSTITIAL": 2,
    "DISPALY_NATIVE": 3,
    "APPWALL": 4,
    "REWARDED_APPWALL": 5,
    "INTERSTITIAL_VIDEO": 6,
    "NATIVE_VIDEO": 7,
    "REWARDED_VIDEO": 8,
    "INSTREAM_VIDEO": 9,
    "INTERACTIVE": 10,
    "MORE_OFFER": 11,
    "SPLASH": 12,
  }

class AdElementTemplate:
  UNKNOWN = 0
  BANNER_IMG = 101
  BANNER = 102
  APPWALL = 201
  INTERSTITIAL = 301
  NATIVE = 401
  NATIVE_IMG = 402
  NATIVE_VIDEO = 403
  NATIVE_IMG_VIDEO = 404
  REWARDED_VIDEO = 501
  FEEDS_VIDEO = 601
  FEEDS_VIDEO_IMG = 602
  RECTANGULAR = 701
  OFFERWALL = 801
  OFFERWALL_IMG_VIDEO = 802
  INTERSTITIAL_SDK = 901
  MOBPOWER = 1001
  ONLINE_API = 1101

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    101: "BANNER_IMG",
    102: "BANNER",
    201: "APPWALL",
    301: "INTERSTITIAL",
    401: "NATIVE",
    402: "NATIVE_IMG",
    403: "NATIVE_VIDEO",
    404: "NATIVE_IMG_VIDEO",
    501: "REWARDED_VIDEO",
    601: "FEEDS_VIDEO",
    602: "FEEDS_VIDEO_IMG",
    701: "RECTANGULAR",
    801: "OFFERWALL",
    802: "OFFERWALL_IMG_VIDEO",
    901: "INTERSTITIAL_SDK",
    1001: "MOBPOWER",
    1101: "ONLINE_API",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "BANNER_IMG": 101,
    "BANNER": 102,
    "APPWALL": 201,
    "INTERSTITIAL": 301,
    "NATIVE": 401,
    "NATIVE_IMG": 402,
    "NATIVE_VIDEO": 403,
    "NATIVE_IMG_VIDEO": 404,
    "REWARDED_VIDEO": 501,
    "FEEDS_VIDEO": 601,
    "FEEDS_VIDEO_IMG": 602,
    "RECTANGULAR": 701,
    "OFFERWALL": 801,
    "OFFERWALL_IMG_VIDEO": 802,
    "INTERSTITIAL_SDK": 901,
    "MOBPOWER": 1001,
    "ONLINE_API": 1101,
  }

class ApiVersion:
  VERSION_1_1 = 1010000
  VERSION_1_2 = 1020000

  _VALUES_TO_NAMES = {
    1010000: "VERSION_1_1",
    1020000: "VERSION_1_2",
  }

  _NAMES_TO_VALUES = {
    "VERSION_1_1": 1010000,
    "VERSION_1_2": 1020000,
  }

class JmIconStatus:
  UNKNOWN = 0
  ACTIVE = 1
  PAUSED = 2
  DELETED = 3

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "ACTIVE",
    2: "PAUSED",
    3: "DELETED",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "ACTIVE": 1,
    "PAUSED": 2,
    "DELETED": 3,
  }

class Clarity:
  SD = 0
  HD = 1
  LD = 2

  _VALUES_TO_NAMES = {
    0: "SD",
    1: "HD",
    2: "LD",
  }

  _NAMES_TO_VALUES = {
    "SD": 0,
    "HD": 1,
    "LD": 2,
  }

class FallBackLevel:
  DEFAULT = 0
  LOW = 1
  HIGH = 2

  _VALUES_TO_NAMES = {
    0: "DEFAULT",
    1: "LOW",
    2: "HIGH",
  }

  _NAMES_TO_VALUES = {
    "DEFAULT": 0,
    "LOW": 1,
    "HIGH": 2,
  }

class RankerServerType:
  TTHREADPOOLSERVER = 0
  TNONBLOCKINGSERVER = 1

  _VALUES_TO_NAMES = {
    0: "TTHREADPOOLSERVER",
    1: "TNONBLOCKINGSERVER",
  }

  _NAMES_TO_VALUES = {
    "TTHREADPOOLSERVER": 0,
    "TNONBLOCKINGSERVER": 1,
  }

class EndCardType:
  DEFAULT = 1
  PLAYABLE = 2
  DYNAMICENDCARD = 3

  _VALUES_TO_NAMES = {
    1: "DEFAULT",
    2: "PLAYABLE",
    3: "DYNAMICENDCARD",
  }

  _NAMES_TO_VALUES = {
    "DEFAULT": 1,
    "PLAYABLE": 2,
    "DYNAMICENDCARD": 3,
  }

class VideoEndType:
  CLOSE_VIDEO = 1
  NORMAL_ENDCARD = 2
  TRANSLUCENT_ENDCARD = 3
  CLOSE_VIDEO_OPEN_WEBVIEW = 4
  CLOSE_VIDEO_OPEN_BROWSER = 5
  OPEN_STOREKIT = 6

  _VALUES_TO_NAMES = {
    1: "CLOSE_VIDEO",
    2: "NORMAL_ENDCARD",
    3: "TRANSLUCENT_ENDCARD",
    4: "CLOSE_VIDEO_OPEN_WEBVIEW",
    5: "CLOSE_VIDEO_OPEN_BROWSER",
    6: "OPEN_STOREKIT",
  }

  _NAMES_TO_VALUES = {
    "CLOSE_VIDEO": 1,
    "NORMAL_ENDCARD": 2,
    "TRANSLUCENT_ENDCARD": 3,
    "CLOSE_VIDEO_OPEN_WEBVIEW": 4,
    "CLOSE_VIDEO_OPEN_BROWSER": 5,
    "OPEN_STOREKIT": 6,
  }

class TemplateURLType:
  UNKNOWN = 0
  URL = 1
  ZIP = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "URL",
    2: "ZIP",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "URL": 1,
    "ZIP": 2,
  }

class TemplateGroup:
  UNKNOWN = 0
  VIDEO_COMMON_ENDCARD = 1
  VIDEO_DYNAMIC_ENDCARD = 2
  VIDEO_PLAYABLE = 3
  ONLY_PLAYABLE = 4
  VIDEO_STOREKIT_ENDCARD = 6
  VIDEO_FULLSCREENCLICK_ENDCARD = 7

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "VIDEO_COMMON_ENDCARD",
    2: "VIDEO_DYNAMIC_ENDCARD",
    3: "VIDEO_PLAYABLE",
    4: "ONLY_PLAYABLE",
    6: "VIDEO_STOREKIT_ENDCARD",
    7: "VIDEO_FULLSCREENCLICK_ENDCARD",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "VIDEO_COMMON_ENDCARD": 1,
    "VIDEO_DYNAMIC_ENDCARD": 2,
    "VIDEO_PLAYABLE": 3,
    "ONLY_PLAYABLE": 4,
    "VIDEO_STOREKIT_ENDCARD": 6,
    "VIDEO_FULLSCREENCLICK_ENDCARD": 7,
  }

class VideoTemplate:
  UNKNOWN = 0
  V1 = 1
  V2 = 2
  V3 = 3
  V4 = 4
  V7 = 7
  V8 = 8
  V9 = 9
  V11 = 11
  DISABLE = -1

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "V1",
    2: "V2",
    3: "V3",
    4: "V4",
    7: "V7",
    8: "V8",
    9: "V9",
    11: "V11",
    -1: "DISABLE",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "V1": 1,
    "V2": 2,
    "V3": 3,
    "V4": 4,
    "V7": 7,
    "V8": 8,
    "V9": 9,
    "V11": 11,
    "DISABLE": -1,
  }

class TemplateClickArea:
  UNKNOWN = 0
  DEFAULT = 1
  IMAGE = 2
  CTA = 3
  ICON = 4
  FULL = 5
  STOREKIT = 6

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "DEFAULT",
    2: "IMAGE",
    3: "CTA",
    4: "ICON",
    5: "FULL",
    6: "STOREKIT",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "DEFAULT": 1,
    "IMAGE": 2,
    "CTA": 3,
    "ICON": 4,
    "FULL": 5,
    "STOREKIT": 6,
  }

class VideoTemplateId:
  UNKNOWN = 0
  DISABLE = -1
  V1_URL = 101
  V1_ZIP = 102
  V1_URL_ZIP = 105
  V2_URL = 201
  V2_ZIP = 202
  V2_URL_ZIP = 205
  V3_URL = 301
  V3_ZIP = 302
  V3_URL_ZIP = 305
  V4_URL = 401
  V4_ZIP = 402
  V4_URL_ZIP = 405
  V7_URL = 701
  V7_ZIP = 702
  V8_URL = 801
  V8_ZIP = 802
  V8_URL_ZIP = 805
  V9_ZIP = 904
  V11_ZIP = 1102

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    -1: "DISABLE",
    101: "V1_URL",
    102: "V1_ZIP",
    105: "V1_URL_ZIP",
    201: "V2_URL",
    202: "V2_ZIP",
    205: "V2_URL_ZIP",
    301: "V3_URL",
    302: "V3_ZIP",
    305: "V3_URL_ZIP",
    401: "V4_URL",
    402: "V4_ZIP",
    405: "V4_URL_ZIP",
    701: "V7_URL",
    702: "V7_ZIP",
    801: "V8_URL",
    802: "V8_ZIP",
    805: "V8_URL_ZIP",
    904: "V9_ZIP",
    1102: "V11_ZIP",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "DISABLE": -1,
    "V1_URL": 101,
    "V1_ZIP": 102,
    "V1_URL_ZIP": 105,
    "V2_URL": 201,
    "V2_ZIP": 202,
    "V2_URL_ZIP": 205,
    "V3_URL": 301,
    "V3_ZIP": 302,
    "V3_URL_ZIP": 305,
    "V4_URL": 401,
    "V4_ZIP": 402,
    "V4_URL_ZIP": 405,
    "V7_URL": 701,
    "V7_ZIP": 702,
    "V8_URL": 801,
    "V8_ZIP": 802,
    "V8_URL_ZIP": 805,
    "V9_ZIP": 904,
    "V11_ZIP": 1102,
  }

class VideoTemplateScreenSize:
  UNKNOWN = 0
  FULL_SCREEN = 1
  HALF_SCREEN = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "FULL_SCREEN",
    2: "HALF_SCREEN",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "FULL_SCREEN": 1,
    "HALF_SCREEN": 2,
  }

class EndCardTemplate:
  UNKNOWN = 0
  DYNAMICENDCARD = -2
  PLAYABLE = -3
  V4 = 4
  V7 = 7
  FULLSCREENCLICK = 8
  STOREKIT = 9
  V1 = 10
  INDUCEDENDCARD = 12
  V14 = 14

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    -2: "DYNAMICENDCARD",
    -3: "PLAYABLE",
    4: "V4",
    7: "V7",
    8: "FULLSCREENCLICK",
    9: "STOREKIT",
    10: "V1",
    12: "INDUCEDENDCARD",
    14: "V14",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "DYNAMICENDCARD": -2,
    "PLAYABLE": -3,
    "V4": 4,
    "V7": 7,
    "FULLSCREENCLICK": 8,
    "STOREKIT": 9,
    "V1": 10,
    "INDUCEDENDCARD": 12,
    "V14": 14,
  }

class EndCardTemplateId:
  UNKNOWN = 0
  DYNAMICENDCARD_URL = -201
  DYNAMICENDCARD_ZIP = -202
  DYNAMICENDCARD_URL_ZIP = -205
  PLAYABLE_URL = -301
  PLAYABLE_ZIP = -302
  PLAYABLE_URL_ZIP = -305
  V4_URL = 401
  V4_ZIP = 402
  V4_URL2 = 403
  V4_ZIP2 = 404
  V4_URL2_ZIP2 = 405
  V7_URL = 701
  V7_ZIP = 702
  V7_URL2 = 703
  V7_ZIP2 = 704
  V7_URL2_ZIP2 = 705
  FULLSCREENCLICK_ZIP = 802
  STOREKIT_ZIP = 902
  V1_URL = 1001
  V1_ZIP = 1002
  V1_URL2 = 1003
  V1_ZIP2 = 1004
  V1_URL2_ZIP2 = 1005
  MULTI_IDS1 = 9999
  MULTI_IDS2 = 9998
  MULTI_IDS3 = 9997
  INDUCEDENDCARD_URL = 1201
  INDUCEDENDCARD_ZIP = 1202
  INDUCEDENDCARD_URL_ZIP = 1205
  V14_ZIP = 1402

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    -201: "DYNAMICENDCARD_URL",
    -202: "DYNAMICENDCARD_ZIP",
    -205: "DYNAMICENDCARD_URL_ZIP",
    -301: "PLAYABLE_URL",
    -302: "PLAYABLE_ZIP",
    -305: "PLAYABLE_URL_ZIP",
    401: "V4_URL",
    402: "V4_ZIP",
    403: "V4_URL2",
    404: "V4_ZIP2",
    405: "V4_URL2_ZIP2",
    701: "V7_URL",
    702: "V7_ZIP",
    703: "V7_URL2",
    704: "V7_ZIP2",
    705: "V7_URL2_ZIP2",
    802: "FULLSCREENCLICK_ZIP",
    902: "STOREKIT_ZIP",
    1001: "V1_URL",
    1002: "V1_ZIP",
    1003: "V1_URL2",
    1004: "V1_ZIP2",
    1005: "V1_URL2_ZIP2",
    9999: "MULTI_IDS1",
    9998: "MULTI_IDS2",
    9997: "MULTI_IDS3",
    1201: "INDUCEDENDCARD_URL",
    1202: "INDUCEDENDCARD_ZIP",
    1205: "INDUCEDENDCARD_URL_ZIP",
    1402: "V14_ZIP",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "DYNAMICENDCARD_URL": -201,
    "DYNAMICENDCARD_ZIP": -202,
    "DYNAMICENDCARD_URL_ZIP": -205,
    "PLAYABLE_URL": -301,
    "PLAYABLE_ZIP": -302,
    "PLAYABLE_URL_ZIP": -305,
    "V4_URL": 401,
    "V4_ZIP": 402,
    "V4_URL2": 403,
    "V4_ZIP2": 404,
    "V4_URL2_ZIP2": 405,
    "V7_URL": 701,
    "V7_ZIP": 702,
    "V7_URL2": 703,
    "V7_ZIP2": 704,
    "V7_URL2_ZIP2": 705,
    "FULLSCREENCLICK_ZIP": 802,
    "STOREKIT_ZIP": 902,
    "V1_URL": 1001,
    "V1_ZIP": 1002,
    "V1_URL2": 1003,
    "V1_ZIP2": 1004,
    "V1_URL2_ZIP2": 1005,
    "MULTI_IDS1": 9999,
    "MULTI_IDS2": 9998,
    "MULTI_IDS3": 9997,
    "INDUCEDENDCARD_URL": 1201,
    "INDUCEDENDCARD_ZIP": 1202,
    "INDUCEDENDCARD_URL_ZIP": 1205,
    "V14_ZIP": 1402,
  }

class MiniCardTemplateId:
  UNKNOWN = 0
  URL = 101
  ZIP = 102
  MULTI_IDS1 = 9999

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    101: "URL",
    102: "ZIP",
    9999: "MULTI_IDS1",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "URL": 101,
    "ZIP": 102,
    "MULTI_IDS1": 9999,
  }

class NumericTypeOperator:
  EQUAL_TO = 1
  GREATER_THAN = 2
  GREATER_THAN_OR_EQUAL_TO = 3
  LESS_THAN = 4
  LESS_THAN_OR_EQUAL_TO = 5

  _VALUES_TO_NAMES = {
    1: "EQUAL_TO",
    2: "GREATER_THAN",
    3: "GREATER_THAN_OR_EQUAL_TO",
    4: "LESS_THAN",
    5: "LESS_THAN_OR_EQUAL_TO",
  }

  _NAMES_TO_VALUES = {
    "EQUAL_TO": 1,
    "GREATER_THAN": 2,
    "GREATER_THAN_OR_EQUAL_TO": 3,
    "LESS_THAN": 4,
    "LESS_THAN_OR_EQUAL_TO": 5,
  }

class CreativeTypeCombinationRule:
  OPTIONAL = 0
  NEED_ONE = 1
  ALL = 100

  _VALUES_TO_NAMES = {
    0: "OPTIONAL",
    1: "NEED_ONE",
    100: "ALL",
  }

  _NAMES_TO_VALUES = {
    "OPTIONAL": 0,
    "NEED_ONE": 1,
    "ALL": 100,
  }

class UnitAppRuleType:
  UNKNOWN = 0
  WHITE = 1
  BLACK = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "WHITE",
    2: "BLACK",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "WHITE": 1,
    "BLACK": 2,
  }

class RankType:
  UNKNOWN = 0
  FIXRANK = 1
  TRYNEW = 2
  SMART_BID = 3

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "FIXRANK",
    2: "TRYNEW",
    3: "SMART_BID",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "FIXRANK": 1,
    "TRYNEW": 2,
    "SMART_BID": 3,
  }

class GaidIdfaNeeds:
  ALL = 0
  ONLY_DEVICE = 1
  ONLY_IP_UA = 2

  _VALUES_TO_NAMES = {
    0: "ALL",
    1: "ONLY_DEVICE",
    2: "ONLY_IP_UA",
  }

  _NAMES_TO_VALUES = {
    "ALL": 0,
    "ONLY_DEVICE": 1,
    "ONLY_IP_UA": 2,
  }

class BigTemplateId:
  UNKNOWN = 0
  SINGLE_SLOT = 101
  SINGLE_SLOT_GOOGLEPLAY = 102
  SELECTABLE_TWO_VIDEO = 201
  SELECTABLE_TWO_VIDEO_PLAY_FIRST = 301
  REWARDPLUS_TWO_SLOT = 401

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    101: "SINGLE_SLOT",
    102: "SINGLE_SLOT_GOOGLEPLAY",
    201: "SELECTABLE_TWO_VIDEO",
    301: "SELECTABLE_TWO_VIDEO_PLAY_FIRST",
    401: "REWARDPLUS_TWO_SLOT",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "SINGLE_SLOT": 101,
    "SINGLE_SLOT_GOOGLEPLAY": 102,
    "SELECTABLE_TWO_VIDEO": 201,
    "SELECTABLE_TWO_VIDEO_PLAY_FIRST": 301,
    "REWARDPLUS_TWO_SLOT": 401,
  }

class BigTemplateRule:
  OPTIONAL_NEED = 0
  NEED_ANY_ONE = 1
  SLOT_LIMIT_TEMPLATE = 2

  _VALUES_TO_NAMES = {
    0: "OPTIONAL_NEED",
    1: "NEED_ANY_ONE",
    2: "SLOT_LIMIT_TEMPLATE",
  }

  _NAMES_TO_VALUES = {
    "OPTIONAL_NEED": 0,
    "NEED_ANY_ONE": 1,
    "SLOT_LIMIT_TEMPLATE": 2,
  }

class TemplateApiFramework:
  UNKNOWN = 0
  MRAID = 1
  JS = 2
  URL = 3
  ZIP = 4

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "MRAID",
    2: "JS",
    3: "URL",
    4: "ZIP",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "MRAID": 1,
    "JS": 2,
    "URL": 3,
    "ZIP": 4,
  }

class ComponentType:
  BANNER = 1
  INTERSTITAL = 2
  DISPLAY_NATIVE = 3
  NATIVE_VIDEO = 4
  VIDEO = 5
  ENDCARD = 6
  MINICARD = 7

  _VALUES_TO_NAMES = {
    1: "BANNER",
    2: "INTERSTITAL",
    3: "DISPLAY_NATIVE",
    4: "NATIVE_VIDEO",
    5: "VIDEO",
    6: "ENDCARD",
    7: "MINICARD",
  }

  _NAMES_TO_VALUES = {
    "BANNER": 1,
    "INTERSTITAL": 2,
    "DISPLAY_NATIVE": 3,
    "NATIVE_VIDEO": 4,
    "VIDEO": 5,
    "ENDCARD": 6,
    "MINICARD": 7,
  }

class TemplateType:
  DEVELOPER_SELF_RENDER = 1
  COMMON = 2
  OFFER_PLAYABLE_RICH_MEDIA = 3
  OFFER_NOT_PLAYABLE_RICH_MEDIA = 4

  _VALUES_TO_NAMES = {
    1: "DEVELOPER_SELF_RENDER",
    2: "COMMON",
    3: "OFFER_PLAYABLE_RICH_MEDIA",
    4: "OFFER_NOT_PLAYABLE_RICH_MEDIA",
  }

  _NAMES_TO_VALUES = {
    "DEVELOPER_SELF_RENDER": 1,
    "COMMON": 2,
    "OFFER_PLAYABLE_RICH_MEDIA": 3,
    "OFFER_NOT_PLAYABLE_RICH_MEDIA": 4,
  }

class TemplateTypeGroup:
  Video_CommonEndcard_Minicard = 1
  Video_NplrmEndcard_Minicard = 2
  Video_PlrmEndcard_Minicard = 3
  PlrmEndcard_Minicard = 4
  Video_Minicard = 5
  Video_PlrmEndcard = 8
  Video_NplrmEndcard = 9
  Video_CommonEndcard = 10
  Video = 11
  PlrmEndcard = 12
  Banner = 13
  Interstitial = 14
  DisplayNative = 15
  NaitveVideo = 16

  _VALUES_TO_NAMES = {
    1: "Video_CommonEndcard_Minicard",
    2: "Video_NplrmEndcard_Minicard",
    3: "Video_PlrmEndcard_Minicard",
    4: "PlrmEndcard_Minicard",
    5: "Video_Minicard",
    8: "Video_PlrmEndcard",
    9: "Video_NplrmEndcard",
    10: "Video_CommonEndcard",
    11: "Video",
    12: "PlrmEndcard",
    13: "Banner",
    14: "Interstitial",
    15: "DisplayNative",
    16: "NaitveVideo",
  }

  _NAMES_TO_VALUES = {
    "Video_CommonEndcard_Minicard": 1,
    "Video_NplrmEndcard_Minicard": 2,
    "Video_PlrmEndcard_Minicard": 3,
    "PlrmEndcard_Minicard": 4,
    "Video_Minicard": 5,
    "Video_PlrmEndcard": 8,
    "Video_NplrmEndcard": 9,
    "Video_CommonEndcard": 10,
    "Video": 11,
    "PlrmEndcard": 12,
    "Banner": 13,
    "Interstitial": 14,
    "DisplayNative": 15,
    "NaitveVideo": 16,
  }

class APIFramework:
  Api_UNKNOWN = 0
  VPAID_1 = 1
  VPAID_2 = 2
  MRAID_1 = 3
  ORMMA = 4
  MRAID_2 = 5
  MRAID_3 = 6

  _VALUES_TO_NAMES = {
    0: "Api_UNKNOWN",
    1: "VPAID_1",
    2: "VPAID_2",
    3: "MRAID_1",
    4: "ORMMA",
    5: "MRAID_2",
    6: "MRAID_3",
  }

  _NAMES_TO_VALUES = {
    "Api_UNKNOWN": 0,
    "VPAID_1": 1,
    "VPAID_2": 2,
    "MRAID_1": 3,
    "ORMMA": 4,
    "MRAID_2": 5,
    "MRAID_3": 6,
  }

class CreativeAttribute:
  Attribute_UNKNOWN = 0
  Attribute_AUDIO_AUTO_PLAY = 1
  Attribute_AUDIO_USER_INITIATED = 2
  Attribute_EXPANDABLE_AUTOMATIC = 3
  Attribute_EXPANDABLE_CLICK_INITIATED = 4
  Attribute_EXPANDABLE_ROLLOVER_INITIATED = 5
  Attribute_VIDEO_IN_BANNER_AUTO_PLAY = 6
  Attribute_VIDEO_IN_BANNER_USER_INITIATED = 7
  Attribute_POP = 8
  Attribute_PROVOCATIVE_OR_SUGGESTIVE = 9
  Attribute_ANNOYING = 10
  Attribute_SURVEYS = 11
  Attribute_TEXT_ONLY = 12
  Attribute_USER_INTERACTIVE = 13
  Attribute_WINDOWS_DIALOG_OR_ALERT_STYLE = 14
  Attribute_HAS_AUDIO_ON_OFF_BUTTON = 15
  Attribute_AD_CAN_BE_SKIPPED = 16
  Attribute_FLASH = 17

  _VALUES_TO_NAMES = {
    0: "Attribute_UNKNOWN",
    1: "Attribute_AUDIO_AUTO_PLAY",
    2: "Attribute_AUDIO_USER_INITIATED",
    3: "Attribute_EXPANDABLE_AUTOMATIC",
    4: "Attribute_EXPANDABLE_CLICK_INITIATED",
    5: "Attribute_EXPANDABLE_ROLLOVER_INITIATED",
    6: "Attribute_VIDEO_IN_BANNER_AUTO_PLAY",
    7: "Attribute_VIDEO_IN_BANNER_USER_INITIATED",
    8: "Attribute_POP",
    9: "Attribute_PROVOCATIVE_OR_SUGGESTIVE",
    10: "Attribute_ANNOYING",
    11: "Attribute_SURVEYS",
    12: "Attribute_TEXT_ONLY",
    13: "Attribute_USER_INTERACTIVE",
    14: "Attribute_WINDOWS_DIALOG_OR_ALERT_STYLE",
    15: "Attribute_HAS_AUDIO_ON_OFF_BUTTON",
    16: "Attribute_AD_CAN_BE_SKIPPED",
    17: "Attribute_FLASH",
  }

  _NAMES_TO_VALUES = {
    "Attribute_UNKNOWN": 0,
    "Attribute_AUDIO_AUTO_PLAY": 1,
    "Attribute_AUDIO_USER_INITIATED": 2,
    "Attribute_EXPANDABLE_AUTOMATIC": 3,
    "Attribute_EXPANDABLE_CLICK_INITIATED": 4,
    "Attribute_EXPANDABLE_ROLLOVER_INITIATED": 5,
    "Attribute_VIDEO_IN_BANNER_AUTO_PLAY": 6,
    "Attribute_VIDEO_IN_BANNER_USER_INITIATED": 7,
    "Attribute_POP": 8,
    "Attribute_PROVOCATIVE_OR_SUGGESTIVE": 9,
    "Attribute_ANNOYING": 10,
    "Attribute_SURVEYS": 11,
    "Attribute_TEXT_ONLY": 12,
    "Attribute_USER_INTERACTIVE": 13,
    "Attribute_WINDOWS_DIALOG_OR_ALERT_STYLE": 14,
    "Attribute_HAS_AUDIO_ON_OFF_BUTTON": 15,
    "Attribute_AD_CAN_BE_SKIPPED": 16,
    "Attribute_FLASH": 17,
  }

class DeviceSupportMd5:
  YES = 1
  NO = 2

  _VALUES_TO_NAMES = {
    1: "YES",
    2: "NO",
  }

  _NAMES_TO_VALUES = {
    "YES": 1,
    "NO": 2,
  }

class DeviceTypeNeeds:
  YES = 1
  NO = 2

  _VALUES_TO_NAMES = {
    1: "YES",
    2: "NO",
  }

  _NAMES_TO_VALUES = {
    "YES": 1,
    "NO": 2,
  }

class DimensionType:
  UNKNOWN = 0
  _3D = 1
  _2D = 2

  _VALUES_TO_NAMES = {
    0: "UNKNOWN",
    1: "_3D",
    2: "_2D",
  }

  _NAMES_TO_VALUES = {
    "UNKNOWN": 0,
    "_3D": 1,
    "_2D": 2,
  }

class CreativePackageType:
  Normal = 0
  Dco = 1
  AbTest = 2

  _VALUES_TO_NAMES = {
    0: "Normal",
    1: "Dco",
    2: "AbTest",
  }

  _NAMES_TO_VALUES = {
    "Normal": 0,
    "Dco": 1,
    "AbTest": 2,
  }

