# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import juno_pb2 as juno__pb2


class JunoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.junoSearch = channel.unary_unary(
                '/juno.JunoService/junoSearch',
                request_serializer=juno__pb2.JunoRequest.SerializeToString,
                response_deserializer=juno__pb2.JunoResponse.FromString,
                )
        self.junoSearchTC = channel.unary_unary(
                '/juno.JunoService/junoSearchTC',
                request_serializer=juno__pb2.JunoRequest.SerializeToString,
                response_deserializer=juno__pb2.JunoResponse.FromString,
                )
        self.junoSearchRtDsp = channel.unary_unary(
                '/juno.JunoService/junoSearchRtDsp',
                request_serializer=juno__pb2.JunoRequest.SerializeToString,
                response_deserializer=juno__pb2.JunoResponse.FromString,
                )


class JunoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def junoSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def junoSearchTC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def junoSearchRtDsp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JunoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'junoSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.junoSearch,
                    request_deserializer=juno__pb2.JunoRequest.FromString,
                    response_serializer=juno__pb2.JunoResponse.SerializeToString,
            ),
            'junoSearchTC': grpc.unary_unary_rpc_method_handler(
                    servicer.junoSearchTC,
                    request_deserializer=juno__pb2.JunoRequest.FromString,
                    response_serializer=juno__pb2.JunoResponse.SerializeToString,
            ),
            'junoSearchRtDsp': grpc.unary_unary_rpc_method_handler(
                    servicer.junoSearchRtDsp,
                    request_deserializer=juno__pb2.JunoRequest.FromString,
                    response_serializer=juno__pb2.JunoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'juno.JunoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JunoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def junoSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/juno.JunoService/junoSearch',
            juno__pb2.JunoRequest.SerializeToString,
            juno__pb2.JunoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def junoSearchTC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/juno.JunoService/junoSearchTC',
            juno__pb2.JunoRequest.SerializeToString,
            juno__pb2.JunoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def junoSearchRtDsp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/juno.JunoService/junoSearchRtDsp',
            juno__pb2.JunoRequest.SerializeToString,
            juno__pb2.JunoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
